
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
              

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: CustomerOrder
      description: "A dbt model for total order price"
      columns:
          - name: c_custkey
            description: "The primary key for customer table"
            tests:
                - unique
                - not_null

    - name: Incremental_Date